const languages: Record<string, string> = {
  eng: "English",
  jpn: "Japanese",
  spa: "Spanish",
  fre: "French",
  fra: "French",
  ger: "German",
  deu: "German",
  ita: "Italian",
  por: "Portuguese",
  rus: "Russian",
  kor: "Korean",
  zho: "Chinese",
  chi: "Chinese",
  ara: "Arabic",
  hin: "Hindi",
  tha: "Thai",
  vie: "Vietnamese",
  ind: "Indonesian",
  may: "Malay",
  msa: "Malay",
  pol: "Polish",
  nld: "Dutch",
  dut: "Dutch",
  swe: "Swedish",
  nor: "Norwegian",
  dan: "Danish",
  fin: "Finnish",
  tur: "Turkish",
  heb: "Hebrew",
  ell: "Greek",
  gre: "Greek",
  ces: "Czech",
  cze: "Czech",
  ron: "Romanian",
  rum: "Romanian",
  hun: "Hungarian",
  ukr: "Ukrainian",
  cat: "Catalan",
  hrv: "Croatian",
  bul: "Bulgarian",
  srp: "Serbian",
  slk: "Slovak",
  slo: "Slovak",
  lit: "Lithuanian",
  lav: "Latvian",
  est: "Estonian",
  tam: "Tamil",
  tel: "Telugu",
  ben: "Bengali",
  urd: "Urdu",
  fil: "Filipino",
  und: "Undetermined",
};

/** Canonical entries for dropdown lists (no duplicate display names). */
export const languageList: { code: string; name: string }[] = [
  { code: "eng", name: "English" },
  { code: "jpn", name: "Japanese" },
  { code: "spa", name: "Spanish" },
  { code: "fre", name: "French" },
  { code: "ger", name: "German" },
  { code: "ita", name: "Italian" },
  { code: "por", name: "Portuguese" },
  { code: "rus", name: "Russian" },
  { code: "kor", name: "Korean" },
  { code: "zho", name: "Chinese" },
  { code: "ara", name: "Arabic" },
  { code: "hin", name: "Hindi" },
  { code: "tha", name: "Thai" },
  { code: "vie", name: "Vietnamese" },
  { code: "ind", name: "Indonesian" },
  { code: "may", name: "Malay" },
  { code: "pol", name: "Polish" },
  { code: "nld", name: "Dutch" },
  { code: "swe", name: "Swedish" },
  { code: "nor", name: "Norwegian" },
  { code: "dan", name: "Danish" },
  { code: "fin", name: "Finnish" },
  { code: "tur", name: "Turkish" },
  { code: "heb", name: "Hebrew" },
  { code: "ell", name: "Greek" },
  { code: "ces", name: "Czech" },
  { code: "ron", name: "Romanian" },
  { code: "hun", name: "Hungarian" },
  { code: "ukr", name: "Ukrainian" },
  { code: "cat", name: "Catalan" },
  { code: "hrv", name: "Croatian" },
  { code: "bul", name: "Bulgarian" },
  { code: "srp", name: "Serbian" },
  { code: "slk", name: "Slovak" },
  { code: "lit", name: "Lithuanian" },
  { code: "lav", name: "Latvian" },
  { code: "est", name: "Estonian" },
  { code: "tam", name: "Tamil" },
  { code: "tel", name: "Telugu" },
  { code: "ben", name: "Bengali" },
  { code: "urd", name: "Urdu" },
  { code: "fil", name: "Filipino" },
];

export function langName(code: string): string {
  return languages[code] ?? code;
}
